services:
  db:
    image: postgres:17.8
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: jbre-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
